"""Scan knowledge/ and regenerate index.md — papers by facet, the relation map,
and what still needs classifying.

    sconix kindex        (or: uv run --project ~/research/os/sconixlib python build_index.py)
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).parent
FACETS = ["object", "intervention_locus", "mechanism", "effect", "evidence"]
RELATIONS = ["builds_on", "alternative_to", "contradicts", "related", "applied_in"]


def parse(md: Path) -> dict:
    text = md.read_text()
    if not text.startswith("---\n"):
        return {"_stem": md.stem, "_path": md.relative_to(ROOT).as_posix()}
    fm = text[4:].split("\n---\n", 1)[0]
    data = yaml.safe_load(fm) or {}
    data["_stem"] = md.stem
    data["_path"] = md.relative_to(ROOT).as_posix()
    return data


def link(p: dict) -> str:
    return f"[{p.get('title', p['_stem'])}]({p['_path']})"


def main() -> None:
    papers = sorted(
        (parse(p) for p in (ROOT / "papers").glob("*.md")),
        key=lambda p: (str(p.get("year", "")), p["_stem"]),
        reverse=True,
    )
    concepts = sorted(parse(p) for p in (ROOT / "concepts").glob("*.md"))
    threads = sorted(parse(p) for p in (ROOT / "threads").glob("*.md"))

    out: list[str] = [
        "# Knowledge index",
        "",
        "_Generated by `sconix kindex` — do not edit by hand._",
        "",
    ]
    by_status: dict[str, int] = defaultdict(int)
    for p in papers:
        by_status[p.get("status", "?")] += 1
    unclassified = [
        p for p in papers if not (p.get("object") and p.get("mechanism") and p.get("effect"))
    ]

    out += [
        f"**{len(papers)} papers** — "
        + ", ".join(f"{k}: {v}" for k, v in sorted(by_status.items()))
        + f" · **{len(concepts)} concepts** · **{len(threads)} threads**",
        "",
    ]

    for facet in FACETS:
        buckets: dict[str, list[dict]] = defaultdict(list)
        for p in papers:
            for v in p.get(facet) or ["(unset)"]:
                buckets[str(v)].append(p)
        out.append(f"## By {facet.replace('_', ' ')}")
        for v in sorted(buckets):
            out.append(f"\n**{v}**")
            out += [f"- {link(p)}" for p in buckets[v]]
        out.append("")

    out.append("## Relation map")
    for p in papers:
        rels = [(r, p.get(r)) for r in RELATIONS if p.get(r)]
        if rels:
            out.append(f"\n**{link(p)}**")
            for r, targets in rels:
                out.append(f"- {r.replace('_', ' ')}: " + ", ".join(f"`{t}`" for t in targets))
    out.append("")

    if threads:
        out.append("## Threads")
        for t in threads:
            out.append(f"- [{t.get('title', t['_stem'])}]({t['_path']}) — {t.get('status', '?')}")
        out.append("")
    if concepts:
        out.append("## Concepts")
        out += [f"- [{c.get('title', c['_stem'])}]({c['_path']})" for c in concepts]
        out.append("")

    if unclassified:
        out.append("## Needs classification (missing object / mechanism / effect)")
        out += [f"- {link(p)}" for p in unclassified]
        out.append("")

    (ROOT / "index.md").write_text("\n".join(out).rstrip() + "\n")
    print(f"index.md: {len(papers)} papers, {len(concepts)} concepts, {len(threads)} threads")
    if unclassified:
        print(f"  {len(unclassified)} paper(s) need classification")


if __name__ == "__main__":
    main()
